# Generated by Django 6.1 on 2026-08-18 07:40

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0039_botuser_comic_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'OTP телефон',
                'verbose_name_plural': 'OTP телефоны',
            },
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('deep_link', models.CharField(blank=True, default='', max_length=512)),
                ('entity_type', models.CharField(blank=True, default='', max_length=64)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_notifications', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Уведомление приложения',
                'verbose_name_plural': 'Уведомления приложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MobileAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=api.models._token, max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('push_token', models.CharField(blank=True, default='', max_length=512)),
                ('push_platform', models.CharField(blank=True, default='', help_text='android | ios', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_tokens', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Мобильный токен',
                'verbose_name_plural': 'Мобильные токены',
            },
        ),
    ]
