# Generated by Django 6.1 on 2026-08-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_mobile_auth_and_notifications'),
        ('database', '0044_botuser_pin_and_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('kind', models.CharField(choices=[('login', 'Вход через Max'), ('reset', 'Сброс PIN'), ('change', 'Смена PIN')], db_index=True, default='login', max_length=16)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('bot_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_challenges', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Код Max/PIN challenge',
                'verbose_name_plural': 'Коды Max/PIN challenge',
                'ordering': ['-created_at'],
            },
        ),
    ]
