# Generated by Django 6.1 on 2026-08-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_botuser_pin_and_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRegistrationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('real_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=16)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Черновик регистрации приложения',
                'verbose_name_plural': 'Черновики регистрации приложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='pinchallenge',
            name='kind',
            field=models.CharField(choices=[('login', 'Вход через Max'), ('reset', 'Сброс PIN'), ('change', 'Смена PIN'), ('register', 'Регистрация в приложении')], db_index=True, default='login', max_length=16),
        ),
    ]
