# Generated by Django 6.1 on 2026-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_botuser_gender_birth_and_app_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appregistrationdraft',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='appregistrationdraft',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
