# Generated by Django 6.0.7 on 2026-07-30 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_bot_token', models.CharField(blank=True, default='', max_length=512, verbose_name='Токен бота MAX')),
                ('allowed_max_user_id', models.CharField(blank=True, default='', help_text='Только этот user_id сможет пользоваться ботом. Оставьте пустым, чтобы запомнить первого.', max_length=64, verbose_name='ID разрешённого пользователя MAX')),
                ('yandex_api_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Yandex API Key')),
                ('yandex_folder_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Yandex Folder ID')),
                ('yandex_model', models.CharField(blank=True, default='yandexgpt-lite', help_text='Например: yandexgpt-lite, yandexgpt, yandexgpt-5-pro', max_length=128, verbose_name='Модель YandexGPT')),
                ('bot_display_name', models.CharField(default='Voitos', max_length=64, verbose_name='Имя помощника')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_user_id', models.CharField(max_length=64, unique=True, verbose_name='MAX user id')),
                ('chat_id', models.CharField(blank=True, default='', max_length=64, verbose_name='MAX chat id')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('username', models.CharField(blank=True, default='', max_length=255, verbose_name='Username')),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_user_text', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Ожидающее действие',
                'verbose_name_plural': 'Ожидающие действия',
            },
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Задача')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('done', 'Выполнена')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Логи активности',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='database_ac_created_25ca54_idx'), models.Index(fields=['kind'], name='database_ac_kind_6d8943_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Помощник'), ('system', 'Система')], max_length=16)),
                ('text', models.TextField()),
                ('is_voice', models.BooleanField(default=False)),
                ('voice_transcript', models.TextField(blank=True, default='')),
                ('max_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('intent', models.CharField(blank=True, default='', max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='database_ch_created_dd6c38_idx'), models.Index(fields=['role'], name='database_ch_role_f81f3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('category', models.CharField(choices=[('purchases', 'Покупки'), ('home', 'Дом'), ('car', 'Автомобиль'), ('finance', 'Финансы'), ('health', 'Здоровье'), ('preferences', 'Предпочтения'), ('people', 'Люди'), ('ideas', 'Идеи'), ('other', 'Прочее')], default='other', max_length=32, verbose_name='Категория')),
                ('source_message', models.TextField(blank=True, default='', verbose_name='Исходное сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Память',
                'verbose_name_plural': 'Память',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='database_me_categor_8b3f3f_idx'), models.Index(fields=['-created_at'], name='database_me_created_61afaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('due_at', models.DateTimeField(verbose_name='Когда напомнить')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['is_done', 'due_at'], name='database_re_is_done_76cdfd_idx')],
            },
        ),
    ]
