# Generated by Django 6.0.7 on 2026-07-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRuntimeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='stopped', max_length=64)),
                ('detail', models.TextField(blank=True, default='')),
                ('bot_name', models.CharField(blank=True, default='', max_length=255)),
                ('bot_username', models.CharField(blank=True, default='', max_length=255)),
                ('last_marker', models.BigIntegerField(blank=True, null=True)),
                ('last_poll_at', models.DateTimeField(blank=True, null=True)),
                ('last_update_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус бота',
                'verbose_name_plural': 'Статус бота',
            },
        ),
    ]
