# Generated by Django 6.0.7 on 2026-07-31 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_botruntimestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'ordering': ['-last_seen_at'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='appsettings',
            name='grace_days',
            field=models.PositiveIntegerField(default=2, verbose_name='Дней на оплату после истечения'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='payment_name',
            field=models.CharField(default='Григорьев Дмитрий Вячеславович', max_length=255, verbose_name='Получатель оплаты'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='payment_phone',
            field=models.CharField(default='89625507832', max_length=32, verbose_name='Телефон для оплаты'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='subscription_price_rub',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена подписки, ₽/мес'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='grace_until',
            field=models.DateTimeField(blank=True, help_text='После истечения подписки ждём оплату до этой даты.', null=True, verbose_name='Льготный период до'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_payment_notice_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='subscription_until',
            field=models.DateTimeField(blank=True, help_text='До этой даты функции бота доступны.', null=True, verbose_name='Подписка до'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='allowed_max_user_id',
            field=models.CharField(blank=True, default='', help_text='Оставьте пустым — бот доступен нескольким пользователям.', max_length=64, verbose_name='Ограничение одного user_id (устарело)'),
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Файл чека')),
                ('image_url', models.URLField(blank=True, default='')),
                ('ocr_text', models.TextField(blank=True, default='', verbose_name='Распознанный текст')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='Дата перевода')),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=64)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('months_granted', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=16)),
                ('ai_notes', models.TextField(blank=True, default='')),
                ('details_match', models.BooleanField(default=False, help_text='Телефон/получатель распознаны и совпали с настройками.', verbose_name='Реквизиты совпали')),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Чек оплаты',
                'verbose_name_plural': 'Чеки оплаты',
                'ordering': ['-created_at'],
            },
        ),
    ]
