# Generated by Django 6.0.7 on 2026-07-31 07:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_reminder_repeat_and_pending_clarify'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('snow', 'Чистка снега'), ('playground', 'Детская площадка'), ('lighting', 'Освещение'), ('road', 'Ремонт дороги')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('locality', models.CharField(max_length=255, verbose_name='Населённый пункт')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая сумма, ₽')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('closed', 'Закрыт')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сервисное мероприятие',
                'verbose_name_plural': 'Сервисные мероприятия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_payee_name',
            field=models.CharField(default='Григорьев Д.В.', max_length=255, verbose_name='Сервис: получатель'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_payee_phone',
            field=models.CharField(default='89625507832', max_length=32, verbose_name='Сервис: телефон'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_payee_status',
            field=models.CharField(default='Самозанятый', max_length=64, verbose_name='Сервис: статус'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_tax_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Собрано через самозанятого, ₽'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='service_tax_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('2400000'), max_digits=14, verbose_name='Лимит самозанятого, ₽'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='profile_admin_note',
            field=models.TextField(blank=True, default='', verbose_name='Заметка по анкете'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='profile_status',
            field=models.CharField(choices=[('incomplete', 'Не заполнена'), ('pending_review', 'Проверить данные'), ('verified', 'Проверена'), ('rejected', 'Отклонена')], default='incomplete', max_length=32, verbose_name='Статус анкеты'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='profile_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='profile_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='real_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя (анкета)'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('profile_submitted', 'Анкета отправлена'), ('profile_verified', 'Анкета проверена'), ('service_offer', 'Сервисное предложение'), ('service_receipt', 'Чек сервисного сбора'), ('service_paid', 'Сервисный сбор оплачен'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Имя в MAX'),
        ),
        migrations.CreateModel(
            name='ServiceInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='К оплате, ₽')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Оплачено, ₽')),
                ('status', models.CharField(choices=[('offered', 'Предложено'), ('paid', 'Оплачено'), ('declined', 'Отказ'), ('cancelled', 'Отменено')], default='offered', max_length=16)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='database.servicecampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_invites', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Предложение сбора',
                'verbose_name_plural': 'Предложения сборов',
                'ordering': ['-offered_at'],
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ServiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='service_receipts/%Y/%m/', verbose_name='Файл чека')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=64)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принят'), ('rejected', 'Отклонён')], default='pending', max_length=16)),
                ('ai_notes', models.TextField(blank=True, default='')),
                ('details_match', models.BooleanField(default=False)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='database.servicecampaign')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='database.serviceinvite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_receipts', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Чек сервисного сбора',
                'verbose_name_plural': 'Чеки сервисных сборов',
                'ordering': ['-created_at'],
            },
        ),
    ]
