# Generated by Django 6.0.7 on 2026-07-31 07:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_service_works_and_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecampaign',
            name='amount_per_user',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма с участника, ₽'),
        ),
        migrations.AlterField(
            model_name='servicecampaign',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Населённый пункт'),
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='service_groups', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Группа жителей',
                'verbose_name_plural': 'Группы жителей',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='servicecampaign',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='database.servicegroup', verbose_name='Группа'),
        ),
    ]
