# Generated by Django 6.0.7 on 2026-07-31 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_service_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecampaign',
            name='event_at',
            field=models.DateTimeField(blank=True, help_text='К этой дате должен быть выполнен сбор; напоминания неоплатившим — за 3 дня, 1 день и 2 часа.', null=True, verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('profile_submitted', 'Анкета отправлена'), ('profile_verified', 'Анкета проверена'), ('service_offer', 'Сервисное предложение'), ('service_receipt', 'Чек сервисного сбора'), ('service_paid', 'Сервисный сбор оплачен'), ('service_notice', 'Уведомление по сбору'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='ServiceCampaignNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('closed', 'Сбор закрыт'), ('surplus', 'Остаток в бюджет'), ('remind_3d', 'Напоминание за 3 дня'), ('remind_1d', 'Напоминание за 1 день'), ('remind_2h', 'Напоминание за 2 часа')], max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='database.servicecampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_notices', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Уведомление по сбору',
                'verbose_name_plural': 'Уведомления по сборам',
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user', 'kind'), name='uniq_campaign_user_notice_kind')],
            },
        ),
    ]
