# Generated by Django 6.0.7 on 2026-07-31 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_campaign_event_and_notices'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecampaign',
            name='work_stage',
            field=models.CharField(choices=[('collecting', 'Сбор денег'), ('work_started', 'Начало работ'), ('work_done', 'Работа выполнена'), ('work_closed', 'Работа закрыта')], default='collecting', max_length=32, verbose_name='Этап работ'),
        ),
        migrations.AddField(
            model_name='servicecampaign',
            name='work_stage_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceCampaignResultPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_results/%Y/%m/', verbose_name='Фото результата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_photos', to='database.servicecampaign')),
            ],
            options={
                'verbose_name': 'Фото результата работ',
                'verbose_name_plural': 'Фото результатов работ',
                'ordering': ['id'],
            },
        ),
    ]
