# Generated by Django 6.0.7 on 2026-07-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_campaign_work_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='days_granted',
            field=models.PositiveIntegerField(default=0, verbose_name='Дней (остаток)'),
        ),
    ]
