# Generated by Django 6.0.7 on 2026-07-31 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_recalc_receipt_days_and_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payment_receipt', 'Чек подписки'), ('service_receipt', 'Сервис-чек'), ('profile_review', 'Проверка анкеты'), ('family_claim', 'Семейная заявка'), ('address_overlap', 'Совпадение адреса')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('done', 'Выполнена'), ('dismissed', 'Скрыта')], default='open', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.PositiveSmallIntegerField(default=50)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, default='', max_length=512)),
                ('source_model', models.CharField(blank=True, default='', max_length=64)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tasks', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Админ-задача',
                'verbose_name_plural': 'Админ-задачи',
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='database_ad_status_719332_idx'), models.Index(fields=['kind', 'status'], name='database_ad_kind_258241_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), models.Q(('source_model', ''), _negated=True)), fields=('kind', 'source_model', 'source_id'), name='uniq_admin_task_source')],
            },
        ),
    ]
