# Generated by Django 6.0.7 on 2026-07-31 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_admin_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCampaignOfferPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service_offers/%Y/%m/', verbose_name='Фото задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_photos', to='database.servicecampaign')),
            ],
            options={
                'verbose_name': 'Фото задачи сбора',
                'verbose_name_plural': 'Фото задач сборов',
                'ordering': ['id'],
            },
        ),
    ]
