# Generated by Django 6.0.7 on 2026-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_campaign_offer_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceipt',
            name='image',
            field=models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Файл чека'),
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='image',
            field=models.FileField(blank=True, upload_to='service_receipts/%Y/%m/', verbose_name='Файл чека'),
        ),
    ]
