# Generated by Django 6.0.7 on 2026-07-31 09:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_receipt_filefield_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexBillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField(verbose_name='Дата расхода')),
                ('amount_rub', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма, ₽')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Факт расходов Yandex',
                'verbose_name_plural': 'Факты расходов Yandex',
                'ordering': ['-for_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='yandex_llm_rub_per_1k',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.40'), help_text='Оценка для дашборда оплаты. Уточните по тарифу в Yandex Cloud.', max_digits=10, verbose_name='YandexGPT, ₽ / 1000 токенов'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='yandex_ocr_rub_per_page',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=10, verbose_name='OCR, ₽ / страница'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='yandex_stt_rub_per_request',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=10, verbose_name='SpeechKit STT, ₽ / запрос'),
        ),
        migrations.CreateModel(
            name='AiUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('llm', 'YandexGPT'), ('stt', 'SpeechKit'), ('ocr', 'OCR')], max_length=16)),
                ('model_name', models.CharField(blank=True, default='', max_length=128)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('units', models.PositiveIntegerField(default=1, help_text='Запросы STT / страницы OCR / иные единицы.')),
                ('estimated_cost_rub', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Расход Yandex AI',
                'verbose_name_plural': 'Расходы Yandex AI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='database_ai_created_5f8399_idx'), models.Index(fields=['kind', '-created_at'], name='database_ai_kind_4455f7_idx')],
            },
        ),
    ]
