# Generated by Django 6.0.7 on 2026-07-31 10:23

import hashlib
from decimal import Decimal

from django.db import migrations, models


def backfill_hashes(apps, schema_editor):
    PaymentReceipt = apps.get_model("database", "PaymentReceipt")
    for receipt in PaymentReceipt.objects.exclude(image="").iterator():
        try:
            field = receipt.image
            if not field:
                continue
            field.open("rb")
            data = field.read()
            field.close()
        except Exception:
            continue
        if not data:
            continue
        receipt.content_hash = hashlib.sha256(data).hexdigest()
        receipt.save(update_fields=["content_hash"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0016_subscription_finance_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentreceipt",
            name="content_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Хеш байтов файла для поиска попиксельно одинаковых чеков.",
                max_length=64,
                verbose_name="SHA-256 файла",
            ),
        ),
        migrations.AlterField(
            model_name="appsettings",
            name="service_tax_collected",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Считается автоматически из принятых чеков подписки и сервисных сборов за текущий год.",
                max_digits=14,
                verbose_name="Собрано через самозанятого, ₽",
            ),
        ),
        migrations.RunPython(backfill_hashes, noop),
    ]
