# Generated by Django 6.0.7 on 2026-07-31 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0017_receipt_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="family_payer",
            field=models.ForeignKey(
                blank=True,
                help_text="Если указан — доступ дублируется с подписки этого члена семьи.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="family_dependents",
                to="database.botuser",
                verbose_name="Подписку оплатил (семья)",
            ),
        ),
    ]
