# Generated by Django 6.0.7 on 2026-07-31 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0018_family_payer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("message_in", "Входящее сообщение"),
                    ("message_out", "Исходящее сообщение"),
                    ("memory_save", "Сохранение памяти"),
                    ("memory_delete", "Удаление памяти"),
                    ("task_create", "Создание задачи"),
                    ("task_done", "Задача выполнена"),
                    ("task_delete", "Удаление задачи"),
                    ("reminder_create", "Создание напоминания"),
                    ("reminder_sent", "Отправка напоминания"),
                    ("reminder_delete", "Удаление напоминания"),
                    ("access_denied", "Отказ в доступе"),
                    ("receipt_submitted", "Чек отправлен"),
                    ("receipt_approved", "Чек принят"),
                    ("receipt_rejected", "Чек отклонён"),
                    ("subscription_expired", "Подписка истекла"),
                    ("profile_submitted", "Анкета отправлена"),
                    ("profile_verified", "Анкета проверена"),
                    ("service_offer", "Сервисное предложение"),
                    ("service_receipt", "Чек сервисного сбора"),
                    ("service_paid", "Сервисный сбор оплачен"),
                    ("service_notice", "Уведомление по сбору"),
                    ("service_wish", "Пожелание по группе"),
                    ("error", "Ошибка"),
                    ("settings", "Настройки"),
                    ("other", "Прочее"),
                ],
                default="other",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="NeighborhoodWish",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Пожелание")),
                ("source_message", models.TextField(blank=True, default="", verbose_name="Исходное сообщение")),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("road", "Дороги"),
                            ("playground", "Детская площадка"),
                            ("lighting", "Освещение"),
                            ("snow", "Чистка снега"),
                            ("dogs", "Собаки / намордники"),
                            ("trash", "Мусор"),
                            ("parking", "Парковка"),
                            ("safety", "Безопасность"),
                            ("green", "Озеленение"),
                            ("other", "Прочее"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                        verbose_name="Тема",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes",
                        to="database.servicegroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishes",
                        to="database.botuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пожелание жителей",
                "verbose_name_plural": "Пожелания жителей",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="neighborhoodwish",
            index=models.Index(fields=["group", "topic"], name="database_ne_group_i_7d2a1e_idx"),
        ),
        migrations.AddIndex(
            model_name="neighborhoodwish",
            index=models.Index(fields=["-created_at"], name="database_ne_created_9c4b2f_idx"),
        ),
    ]
