# Generated by Django 6.0.7 on 2026-08-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_neighborhood_wishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('tractor', 'Трактор-погрузчик'), ('truck', 'Камаз / грузовой')], max_length=32)),
                ('status', models.CharField(choices=[('offered', 'Предложено'), ('counter_offer', 'Другое время'), ('accepted', 'Согласен'), ('declined', 'Отказ'), ('rejected_time', 'Время отклонено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='offered', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Время выезда / работ для этого исполнителя.', null=True, verbose_name='Назначенное время')),
                ('proposed_at', models.DateTimeField(blank=True, null=True, verbose_name='Предложенное исполнителем время')),
                ('counter_deadline', models.DateTimeField(blank=True, help_text='20 минут с момента предложения другого времени.', null=True, verbose_name='Дедлайн ответа на другое время')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('residents_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Назначение исполнителя',
                'verbose_name_plural': 'Назначения исполнителей',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('tractor', 'Трактор-погрузчик'), ('truck', 'Камаз / грузовой')], max_length=32, verbose_name='Тип техники')),
                ('equipment_label', models.CharField(blank=True, default='', max_length=255, verbose_name='Модель / описание')),
                ('plate_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Госномер')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон')),
                ('locality', models.CharField(blank=True, default='', max_length=255, verbose_name='Населённый пункт')),
                ('status', models.CharField(choices=[('pending_review', 'На проверке'), ('verified', 'Проверен'), ('rejected', 'Отклонён'), ('disabled', 'Отключён')], default='pending_review', max_length=32)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['equipment_type', 'user_id'],
            },
        ),
        migrations.RenameIndex(
            model_name='neighborhoodwish',
            new_name='database_ne_group_i_a97637_idx',
            old_name='database_ne_group_i_7d2a1e_idx',
        ),
        migrations.RenameIndex(
            model_name='neighborhoodwish',
            new_name='database_ne_created_8c9bf0_idx',
            old_name='database_ne_created_9c4b2f_idx',
        ),
        migrations.AddField(
            model_name='servicecampaign',
            name='needs_snow_haul',
            field=models.BooleanField(default=False, help_text='Для чистки снега: подбирать водителей грузовых (камаз) на вывоз.', verbose_name='Нужен вывоз снега'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('profile_submitted', 'Анкета отправлена'), ('profile_verified', 'Анкета проверена'), ('service_offer', 'Сервисное предложение'), ('service_receipt', 'Чек сервисного сбора'), ('service_paid', 'Сервисный сбор оплачен'), ('service_notice', 'Уведомление по сбору'), ('service_wish', 'Пожелание по группе'), ('contractor_register', 'Регистрация исполнителя'), ('contractor_offer', 'Предложение исполнителю'), ('contractor_reply', 'Ответ исполнителя'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='kind',
            field=models.CharField(choices=[('payment_receipt', 'Чек подписки'), ('service_receipt', 'Сервис-чек'), ('profile_review', 'Проверка анкеты'), ('family_claim', 'Семейная заявка'), ('address_overlap', 'Совпадение адреса'), ('contractor_review', 'Проверка исполнителя'), ('contractor_counter', 'Другое время исполнителя')], max_length=32),
        ),
        migrations.AddField(
            model_name='campaignassignment',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='database.servicecampaign'),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to='database.botuser'),
        ),
        migrations.AddField(
            model_name='campaignassignment',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='database.contractorprofile'),
        ),
        migrations.AddConstraint(
            model_name='campaignassignment',
            constraint=models.UniqueConstraint(fields=('campaign', 'contractor'), name='uniq_campaign_contractor_assignment'),
        ),
    ]
