# Generated by Django 6.0.7 on 2026-08-01 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_service_contractors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Например: Сбер, Тинькофф, Альфа.', max_length=255, verbose_name='Банк для перевода'),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='payout_phone',
            field=models.CharField(blank=True, default='', help_text='Если отличается от телефона для связи — на него переводят оплату за работу.', max_length=32, verbose_name='Телефон для перевода денег'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('profile_submitted', 'Анкета отправлена'), ('profile_verified', 'Анкета проверена'), ('service_offer', 'Сервисное предложение'), ('service_receipt', 'Чек сервисного сбора'), ('service_paid', 'Сервисный сбор оплачен'), ('service_notice', 'Уведомление по сбору'), ('service_wish', 'Пожелание по группе'), ('contractor_register', 'Регистрация исполнителя'), ('contractor_offer', 'Предложение исполнителю'), ('contractor_reply', 'Ответ исполнителя'), ('contractor_payout', 'Оплата исполнителю'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон для связи'),
        ),
        migrations.CreateModel(
            name='ContractorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма перевода, ₽')),
                ('receipt_image', models.FileField(upload_to='contractor_payouts/%Y/%m/', verbose_name='Чек перевода')),
                ('bank_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Банк')),
                ('payout_phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Телефон получателя')),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residents_notified_at', models.DateTimeField(blank=True, null=True)),
                ('contractor_notified_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='database.campaignassignment')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_payouts', to='database.servicecampaign')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='database.contractorprofile')),
            ],
            options={
                'verbose_name': 'Оплата исполнителю',
                'verbose_name_plural': 'Оплаты исполнителям',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'assignment'), name='uniq_campaign_assignment_payout')],
            },
        ),
    ]
