# Generated by Django 6.0.7 on 2026-08-02 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_contractor_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='citizen_score',
            field=models.PositiveSmallIntegerField(default=100, help_text='0–100. Пользователю не показывается. По умолчанию 100.', verbose_name='Внутренний рейтинг гражданина'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('profile_submitted', 'Анкета отправлена'), ('profile_verified', 'Анкета проверена'), ('service_offer', 'Сервисное предложение'), ('service_receipt', 'Чек сервисного сбора'), ('service_paid', 'Сервисный сбор оплачен'), ('service_notice', 'Уведомление по сбору'), ('service_wish', 'Пожелание по группе'), ('volunteer_ask', 'Вопрос о помощи на мероприятии'), ('volunteer_reply', 'Ответ о помощи на мероприятии'), ('contractor_register', 'Регистрация исполнителя'), ('contractor_offer', 'Предложение исполнителю'), ('contractor_reply', 'Ответ исполнителя'), ('contractor_payout', 'Оплата исполнителю'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='VolunteerHelpAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('yes', 'Поможет'), ('no', 'Не поможет')], default='pending', max_length=16)),
                ('score_delta', models.IntegerField(default=0, verbose_name='Изменение рейтинга')),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_asks', to='database.servicecampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_asks', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Вопрос о помощи',
                'verbose_name_plural': 'Вопросы о помощи',
                'ordering': ['-asked_at'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user'), name='uniq_volunteer_ask_campaign_user')],
            },
        ),
    ]
