# Generated by Django 6.0.7 on 2026-08-02 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_citizen_score_volunteer_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignResidentHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Назначен'), ('cancelled', 'Снят')], default='assigned', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_helpers', to='database.servicecampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_helper_roles', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Исполнитель из группы',
                'verbose_name_plural': 'Исполнители из группы',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user'), name='uniq_campaign_resident_helper')],
            },
        ),
    ]
