# Generated by Django 6.1 on 2026-08-14 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_panel_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('requires_qualification_docs', models.BooleanField(default=False, verbose_name='Нужны подтверждающие документы о квалификации')),
                ('is_equipment', models.BooleanField(default=False, help_text='Трактор, камаз и т.п. — при регистрации спрашиваем технику.', verbose_name='Техника (госномер / модель)')),
                ('for_snow', models.BooleanField(default=False, verbose_name='Для уборки снега')),
                ('for_road', models.BooleanField(default=False, verbose_name='Для дорожных работ')),
                ('for_snow_haul', models.BooleanField(default=False, help_text='Например камаз — только если в сборе включён вывоз.', verbose_name='Нужен при вывозе снега')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Роль исполнителя',
                'verbose_name_plural': 'Роли исполнителей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='qualification_doc',
            field=models.FileField(blank=True, upload_to='contractor_docs/%Y/%m/', verbose_name='Документ о квалификации'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('profile_submitted', 'Анкета отправлена'), ('profile_verified', 'Анкета проверена'), ('service_offer', 'Сервисное предложение'), ('service_receipt', 'Чек сервисного сбора'), ('service_paid', 'Сервисный сбор оплачен'), ('service_notice', 'Уведомление по сбору'), ('service_wish', 'Пожелание по группе'), ('volunteer_ask', 'Вопрос о помощи на мероприятии'), ('volunteer_reply', 'Ответ о помощи на мероприятии'), ('contractor_register', 'Регистрация исполнителя'), ('contractor_offer', 'Предложение исполнителю'), ('contractor_reply', 'Ответ исполнителя'), ('contractor_payout', 'Оплата исполнителю'), ('work_request', 'Заявка на исполнителя'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='kind',
            field=models.CharField(choices=[('payment_receipt', 'Чек подписки'), ('service_receipt', 'Сервис-чек'), ('profile_review', 'Проверка анкеты'), ('family_claim', 'Семейная заявка'), ('address_overlap', 'Совпадение адреса'), ('contractor_review', 'Проверка исполнителя'), ('contractor_counter', 'Другое время исполнителя'), ('work_request', 'Заявка на исполнителя')], max_length=32),
        ),
        migrations.AlterField(
            model_name='campaignassignment',
            name='equipment_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='equipment_label',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Модель / описание / специализация'),
        ),
        migrations.AlterField(
            model_name='contractorprofile',
            name='equipment_type',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Совпадает с ExecutorRole.code (tractor/truck/…).', max_length=64, verbose_name='Код роли / тип техники'),
        ),
        migrations.AddField(
            model_name='contractorprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contractors', to='database.executorrole', verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='WorkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('status', models.CharField(choices=[('pending', 'Новая'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=16)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_requests', to='database.executorrole', verbose_name='Нужная роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_requests', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Заявка на исполнителя',
                'verbose_name_plural': 'Заявки на исполнителей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkRequestPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='work_requests/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='database.workrequest')),
            ],
            options={
                'verbose_name': 'Фото заявки',
                'verbose_name_plural': 'Фото заявок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PanelActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Действие')),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Лог действия менеджера',
                'verbose_name_plural': 'Логи действий менеджеров',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='database_pa_actor_i_b5a110_idx')],
            },
        ),
    ]
