# Generated by Django 6.1 on 2026-08-14 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_work_request_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='workrequest',
            name='client_confirm_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Когда спросить клиента'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='client_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='commission_admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Комиссия 10%, ₽'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='commission_receipt',
            field=models.FileField(blank=True, null=True, upload_to='work_commission_receipts/%Y/%m/', verbose_name='Чек комиссии 10%'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='commission_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='commission_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('awaiting', 'Ждём оплату 10%'), ('pending_review', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='commission_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='confirmed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по подтверждению клиента, ₽'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='executor_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='job_receipt',
            field=models.FileField(blank=True, null=True, upload_to='work_job_receipts/%Y/%m/', verbose_name='Чек оплаты работы (перевод)'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='pay_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Перевод'), ('cash', 'Наличные')], default='', max_length=16, verbose_name='Способ оплаты работы'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='reported_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма по отчёту исполнителя, ₽'),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='kind',
            field=models.CharField(choices=[('payment_receipt', 'Чек подписки'), ('service_receipt', 'Сервис-чек'), ('profile_review', 'Проверка анкеты'), ('family_claim', 'Семейная заявка'), ('address_overlap', 'Совпадение адреса'), ('contractor_review', 'Проверка исполнителя'), ('contractor_counter', 'Другое время исполнителя'), ('work_request', 'Заявка на исполнителя'), ('work_commission', 'Комиссия исполнителя 10%')], max_length=32),
        ),
        migrations.AlterField(
            model_name='workrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Новая'), ('offering', 'Ищем исполнителя'), ('in_progress', 'В работе'), ('awaiting_client', 'Ждём подтверждения клиента'), ('awaiting_commission', 'Ждём комиссию 10%'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=32),
        ),
        migrations.CreateModel(
            name='ScheduledBotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=64)),
                ('text', models.TextField()),
                ('send_at', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_bot_messages', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Отложенное сообщение бота',
                'verbose_name_plural': 'Отложенные сообщения бота',
                'ordering': ['send_at', 'id'],
                'indexes': [models.Index(fields=['sent_at', 'cancelled_at', 'send_at'], name='database_sc_sent_at_424696_idx')],
            },
        ),
    ]
