# Generated by Django 6.1 on 2026-08-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_multi_role_contractors'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_topic', models.CharField(blank=True, default='', max_length=32)),
                ('will_do', models.BooleanField(default=False)),
                ('raw_reply', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Голос по пожеланиям',
                'verbose_name_plural': 'Голоса по пожеланиям',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='admintask',
            name='kind',
            field=models.CharField(choices=[('payment_receipt', 'Чек подписки'), ('service_receipt', 'Сервис-чек'), ('profile_review', 'Проверка анкеты'), ('family_claim', 'Семейная заявка'), ('address_overlap', 'Совпадение адреса'), ('contractor_review', 'Проверка исполнителя'), ('contractor_counter', 'Другое время исполнителя'), ('work_request', 'Заявка на исполнителя'), ('work_commission', 'Комиссия исполнителя 10%'), ('wish_ballot', 'Сбор по итогам голосования')], max_length=32),
        ),
        migrations.CreateModel(
            name='WishPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Приём пожеланий'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_periods', to='database.servicegroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Период пожеланий',
                'verbose_name_plural': 'Периоды пожеланий',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='WishBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('voting', 'Голосование'), ('won', 'Есть победитель'), ('completed', 'Сбор создан'), ('cancelled', 'Отменено')], db_index=True, default='voting', max_length=16)),
                ('options', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('voting_ends_at', models.DateTimeField()),
                ('tallied_at', models.DateTimeField(blank=True, null=True)),
                ('winner_topic', models.CharField(blank=True, default='', max_length=32)),
                ('winner_label', models.CharField(blank=True, default='', max_length=128)),
                ('winner_summary', models.TextField(blank=True, default='')),
                ('campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wish_ballot', to='database.servicecampaign', verbose_name='Сбор по итогам')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_ballots', to='database.servicegroup', verbose_name='Группа')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='database.wishperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Голосование по пожеланиям',
                'verbose_name_plural': 'Голосования по пожеланиям',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='neighborhoodwish',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishes', to='database.wishperiod', verbose_name='Период подачи'),
        ),
        migrations.AddIndex(
            model_name='neighborhoodwish',
            index=models.Index(fields=['period', 'topic'], name='database_ne_period__908f33_idx'),
        ),
        migrations.AddField(
            model_name='wishvote',
            name='ballot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='database.wishballot'),
        ),
        migrations.AddField(
            model_name='wishvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_votes', to='database.botuser'),
        ),
        migrations.AddIndex(
            model_name='wishperiod',
            index=models.Index(fields=['group', 'status'], name='database_wi_group_i_939949_idx'),
        ),
        migrations.AddIndex(
            model_name='wishballot',
            index=models.Index(fields=['group', 'status'], name='database_wi_group_i_7d607a_idx'),
        ),
        migrations.AddIndex(
            model_name='wishballot',
            index=models.Index(fields=['status', 'voting_ends_at'], name='database_wi_status_dd4b84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishvote',
            unique_together={('ballot', 'user')},
        ),
    ]
