# Generated by Django 6.1 on 2026-08-17 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0036_wish_ballot_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerSurveyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting', 'Сбор ответов'), ('closed', 'Закрыт')], db_index=True, default='collecting', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='Саммари ИИ')),
                ('ai_summarized_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_surveys', to='database.servicegroup', verbose_name='Группа')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_survey_periods', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'Опрос менеджера',
                'verbose_name_plural': 'Опросы менеджеров',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerSurveyAILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_survey_ai_logs', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='database.managersurveyperiod')),
            ],
            options={
                'verbose_name': 'Лог ИИ по менеджеру',
                'verbose_name_plural': 'Логи ИИ по менеджерам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagerSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='database.managersurveyperiod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_survey_responses', to='database.botuser')),
            ],
            options={
                'verbose_name': 'Ответ опроса менеджера',
                'verbose_name_plural': 'Ответы опросов менеджеров',
                'ordering': ['score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='managersurveyperiod',
            index=models.Index(fields=['group', 'status'], name='database_ma_group_i_157595_idx'),
        ),
        migrations.AddIndex(
            model_name='managersurveyperiod',
            index=models.Index(fields=['manager', '-started_at'], name='database_ma_manager_1ba7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='managersurveyperiod',
            index=models.Index(fields=['status', 'ends_at'], name='database_ma_status_465b44_idx'),
        ),
        migrations.AddIndex(
            model_name='managersurveyailog',
            index=models.Index(fields=['manager', '-created_at'], name='database_ma_manager_faa8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='managersurveyresponse',
            index=models.Index(fields=['period', 'score'], name='database_ma_period__a8cffa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='managersurveyresponse',
            unique_together={('period', 'user')},
        ),
    ]
