# Generated by Django 6.1 on 2026-08-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0037_manager_quality_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorrole',
            name='requires_work_photos',
            field=models.BooleanField(default=True, help_text='Если выключено — житель вызывает мастера без фото (маникюр и т.п.).', verbose_name='Нужны фото при записи заявки'),
        ),
    ]
