# Generated by Django 6.1 on 2026-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0038_executorrole_requires_work_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Онбординг завершён'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='onboarding_reward_granted',
            field=models.BooleanField(default=False, help_text='После 5/5 историй подписка продлевается на 1 месяц один раз.', verbose_name='Месяц за онбординг выдан'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='onboarding_steps',
            field=models.JSONField(blank=True, default=list, help_text='Коды просмотренных комиксов: snow, playground, electrician, manicure, computer.', verbose_name='Пройденные истории онбординга'),
        ),
    ]
