# Generated by Django 6.1 on 2026-08-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0043_group_chat_read_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='feedbackticket',
            new_name='database_fe_status_fd4f0b_idx',
            old_name='database_fe_status_9a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackticket',
            new_name='database_fe_kind_19585b_idx',
            old_name='database_fe_kind_9a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='feedbackticket',
            new_name='database_fe_user_id_86a913_idx',
            old_name='database_fe_user_9a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='groupchatmessage',
            new_name='database_gr_group_i_cfa01b_idx',
            old_name='database_gr_group_i_7a1c2d_idx',
        ),
        migrations.RenameIndex(
            model_name='groupchatmessage',
            new_name='database_gr_group_i_7a8d1d_idx',
            old_name='database_gr_group_i_9b4e0f_idx',
        ),
        migrations.RenameIndex(
            model_name='groupchatreadstate',
            new_name='database_gr_user_id_e52305_idx',
            old_name='database_gr_user_id_chatrd_idx',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='max_bot_open_url',
            field=models.CharField(blank=True, default='', help_text='Например https://max.ru/voitos_bot — кнопка «Войти через Max».', max_length=512, verbose_name='Ссылка на бота MAX (для приложения)'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='pin_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Неудачные попытки PIN'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='pin_hash',
            field=models.CharField(blank=True, default='', help_text='Постоянный 4-значный PIN для входа в приложение (только hash).', max_length=128, verbose_name='Хеш PIN приложения'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='PIN заблокирован до'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='kind',
            field=models.CharField(choices=[('message_in', 'Входящее сообщение'), ('message_out', 'Исходящее сообщение'), ('memory_save', 'Сохранение памяти'), ('memory_delete', 'Удаление памяти'), ('task_create', 'Создание задачи'), ('task_done', 'Задача выполнена'), ('task_delete', 'Удаление задачи'), ('reminder_create', 'Создание напоминания'), ('reminder_sent', 'Отправка напоминания'), ('reminder_delete', 'Удаление напоминания'), ('access_denied', 'Отказ в доступе'), ('receipt_submitted', 'Чек отправлен'), ('receipt_approved', 'Чек принят'), ('receipt_rejected', 'Чек отклонён'), ('subscription_expired', 'Подписка истекла'), ('profile_submitted', 'Анкета отправлена'), ('profile_verified', 'Анкета проверена'), ('service_offer', 'Сервисное предложение'), ('service_receipt', 'Чек сервисного сбора'), ('service_paid', 'Сервисный сбор оплачен'), ('service_notice', 'Уведомление по сбору'), ('service_wish', 'Пожелание по группе'), ('feedback', 'Обратная связь'), ('volunteer_ask', 'Вопрос о помощи на мероприятии'), ('volunteer_reply', 'Ответ о помощи на мероприятии'), ('contractor_register', 'Регистрация исполнителя'), ('contractor_offer', 'Предложение исполнителю'), ('contractor_reply', 'Ответ исполнителя'), ('contractor_payout', 'Оплата исполнителю'), ('work_request', 'Заявка на исполнителя'), ('error', 'Ошибка'), ('settings', 'Настройки'), ('other', 'Прочее')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='kind',
            field=models.CharField(choices=[('payment_receipt', 'Чек подписки'), ('service_receipt', 'Сервис-чек'), ('profile_review', 'Проверка анкеты'), ('family_claim', 'Семейная заявка'), ('address_overlap', 'Совпадение адреса'), ('contractor_review', 'Проверка исполнителя'), ('contractor_counter', 'Другое время исполнителя'), ('work_request', 'Заявка на исполнителя'), ('work_commission', 'Комиссия исполнителя 10%'), ('wish_ballot', 'Сбор по итогам голосования'), ('feedback', 'Обратная связь / баг')], max_length=32),
        ),
    ]
