# Generated by Django 6.1 on 2026-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_botuser_pin_and_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='mobile_apk_url',
            field=models.CharField(blank=True, default='', help_text='Опционально: куда отправить пользователя за новой сборкой.', max_length=512, verbose_name='Ссылка на APK для обновления'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mobile_latest_version_code',
            field=models.PositiveIntegerField(default=7, verbose_name='Актуальный versionCode'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mobile_latest_version_name',
            field=models.CharField(blank=True, default='0.2.3-kmp', max_length=64, verbose_name='Актуальная versionName'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='mobile_min_version_code',
            field=models.PositiveIntegerField(default=7, help_text='Клиенты со меньшим versionCode увидят требование обновить приложение.', verbose_name='Мин. versionCode приложения'),
        ),
    ]
