# Generated by Django 6.1 on 2026-08-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0045_mobile_app_version_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], default='', max_length=16, verbose_name='Пол'),
        ),
    ]
