# Generated by Django 6.1 on 2026-08-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_botuser_gender_birth_and_app_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='max_bot_open_url',
            field=models.CharField(blank=True, default='https://max.ru/se13602985_1_bot', help_text='Например https://max.ru/se13602985_1_bot — кнопка «Перейти в Max».', max_length=512, verbose_name='Ссылка на бота MAX (для приложения)'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_latest_version_code',
            field=models.PositiveIntegerField(default=9, verbose_name='Актуальный versionCode'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_latest_version_name',
            field=models.CharField(blank=True, default='0.2.5-kmp', max_length=64, verbose_name='Актуальная versionName'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_min_version_code',
            field=models.PositiveIntegerField(default=9, help_text='Клиенты со меньшим versionCode увидят требование обновить приложение.', verbose_name='Мин. versionCode приложения'),
        ),
    ]
