# Generated by Django 6.1 on 2026-08-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0047_max_bot_url_and_version_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_latest_version_code',
            field=models.PositiveIntegerField(default=10, verbose_name='Актуальный versionCode'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_latest_version_name',
            field=models.CharField(blank=True, default='0.2.6-kmp', max_length=64, verbose_name='Актуальная versionName'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_min_version_code',
            field=models.PositiveIntegerField(default=10, help_text='Клиенты со меньшим versionCode увидят требование обновить приложение.', verbose_name='Мин. versionCode приложения'),
        ),
    ]
