# Generated by Django 6.1 on 2026-08-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0050_app_version_0_2_8'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_latest_version_code',
            field=models.PositiveIntegerField(default=13, verbose_name='Актуальный versionCode'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_latest_version_name',
            field=models.CharField(blank=True, default='0.2.9-kmp', max_length=64, verbose_name='Актуальная versionName'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='mobile_min_version_code',
            field=models.PositiveIntegerField(default=13, help_text='Клиенты со меньшим versionCode увидят требование обновить приложение.', verbose_name='Мин. versionCode приложения'),
        ),
    ]
