# Generated by Django 6.1 on 2026-08-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_app_version_0_2_27'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='executorroleproposal',
            new_name='database_ex_status_d1b1ca_idx',
            old_name='database_ex_status_7c8a0a_idx',
        ),
        migrations.RenameIndex(
            model_name='executorroleproposal',
            new_name='database_ex_user_id_2da9cb_idx',
            old_name='database_ex_user_id_9f2b1c_idx',
        ),
        migrations.AddField(
            model_name='workrequest',
            name='amount_mismatch_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Доплата комиссии при расхождении, ₽'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='amount_mismatch_message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение исполнителю о расхождении (экран Работа)'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='client_cancel_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий клиента при отмене'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='client_marked_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Клиент нажал «Работа выполнена»'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='client_pay_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Перевод'), ('cash', 'Наличные')], default='', max_length=16, verbose_name='Способ оплаты (со слов клиента)'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='executor_cancel_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий исполнителя при отмене'),
        ),
        migrations.AddField(
            model_name='workrequest',
            name='executor_marked_done_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Исполнитель нажал «Работа выполнена»'),
        ),
        migrations.AlterField(
            model_name='admintask',
            name='kind',
            field=models.CharField(choices=[('payment_receipt', 'Чек подписки'), ('service_receipt', 'Сервис-чек'), ('profile_review', 'Проверка анкеты'), ('family_claim', 'Семейная заявка'), ('address_overlap', 'Совпадение адреса'), ('contractor_review', 'Проверка исполнителя'), ('contractor_counter', 'Другое время исполнителя'), ('work_request', 'Заявка на исполнителя'), ('work_commission', 'Комиссия исполнителя 10%'), ('work_amount_mismatch', 'Расхождение суммы по заявке'), ('wish_ballot', 'Сбор по итогам голосования'), ('feedback', 'Обратная связь / баг'), ('role_proposal', 'Заявка на новую роль')], max_length=32),
        ),
    ]
