from django.urls import path

from panel import executor_views, views

app_name = "panel"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("", views.users_list, name="users"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("tasks/today/", views.admin_tasks_today, name="admin_tasks_today"),
    path("tasks/today/feed/", views.admin_tasks_feed, name="admin_tasks_feed"),
    path("tasks/<int:pk>/done/", views.admin_task_done, name="admin_task_done"),
    path("tasks/<int:pk>/dismiss/", views.admin_task_dismiss, name="admin_task_dismiss"),
    path("tasks/address-scan/", views.admin_address_scan, name="admin_address_scan"),
    path("users/<int:user_id>/", views.user_dashboard, name="user_dashboard"),
    path("users/<int:user_id>/profile/", views.user_profile_verify, name="user_profile_verify"),
    path("users/<int:user_id>/family/", views.user_family_link, name="user_family_link"),
    path("users/<int:user_id>/messages/", views.user_messages, name="user_messages"),
    path("users/<int:user_id>/memories/", views.user_memories, name="user_memories"),
    path("users/<int:user_id>/tasks/", views.user_tasks, name="user_tasks"),
    path("users/<int:user_id>/reminders/", views.user_reminders, name="user_reminders"),
    path("users/<int:user_id>/logs/", views.user_logs, name="user_logs"),
    path("users/<int:user_id>/receipts/", views.user_receipts, name="user_receipts"),
    path("receipts/", views.receipts_list, name="receipts"),
    path("receipts/<int:pk>/approve/", views.receipt_approve, name="receipt_approve"),
    path("receipts/<int:pk>/reject/", views.receipt_reject, name="receipt_reject"),
    path("receipts/<int:pk>/delete/", views.receipt_delete, name="receipt_delete"),
    path("services/", views.services_home, name="services"),
    path("services/archive/", views.services_archive, name="services_archive"),
    path("services/wishes/", views.services_wishes, name="services_wishes"),
    path("services/groups/", views.services_groups, name="services_groups"),
    path("services/ranking/", views.services_ranking, name="services_ranking"),
    path("clients-map/", views.clients_map, name="clients_map"),
    path("earnings-forecast/", views.earnings_forecast, name="earnings_forecast"),
    path("contractors/", views.contractors_list, name="contractors"),
    path("executor-roles/", executor_views.executor_roles, name="executor_roles"),
    path("work-requests/", executor_views.work_requests_list, name="work_requests"),
    path(
        "work-requests/<int:pk>/",
        executor_views.work_request_detail,
        name="work_request_detail",
    ),
    path("manager-logs/", executor_views.manager_logs_list, name="manager_logs"),
    path(
        "manager-logs/<int:user_id>/",
        executor_views.manager_log_detail,
        name="manager_log_detail",
    ),
    path("bot-users/search/", views.bot_users_search, name="bot_users_search"),
    path("services/groups/<int:pk>/", views.service_group_edit, name="service_group_edit"),
    path(
        "services/campaigns/<int:pk>/",
        views.service_campaign_detail,
        name="service_campaign_detail",
    ),
    path(
        "services/receipts/<int:pk>/approve/",
        views.service_receipt_approve,
        name="service_receipt_approve",
    ),
    path(
        "services/receipts/<int:pk>/reject/",
        views.service_receipt_reject,
        name="service_receipt_reject",
    ),
    path("services/<str:category>/", views.services_category, name="services_category"),
    path(
        "services/<str:category>/new/",
        views.service_campaign_create,
        name="service_campaign_create",
    ),
    path("settings/", views.settings_view, name="settings"),
    path("check-max/", views.check_max, name="check_max"),
    path("delete/memory/<int:pk>/", views.delete_memory, name="delete_memory"),
    path("delete/task/<int:pk>/", views.delete_task, name="delete_task"),
    path("delete/reminder/<int:pk>/", views.delete_reminder, name="delete_reminder"),
    path("delete/message/<int:pk>/", views.delete_message, name="delete_message"),
    path("dump/", views.dump_now, name="dump_now"),
]
