from django.urls import path

from api import auth_views, views

app_name = "api"

urlpatterns = [
    path("health", views.health, name="health"),
    path("auth/config", auth_views.auth_config, name="auth_config"),
    path("auth/phone/start", auth_views.phone_start, name="auth_phone_start"),
    path("auth/phone/verify", auth_views.phone_verify, name="auth_phone_verify"),
    path("auth/phone/login-request", auth_views.phone_login_request, name="auth_phone_login_request"),
    path("auth/phone/login-verify", auth_views.phone_login_verify, name="auth_phone_login_verify"),
    path("auth/register/start", auth_views.register_start, name="auth_register_start"),
    path("auth/register/confirm", auth_views.register_confirm, name="auth_register_confirm"),
    path("auth/max/start", auth_views.max_start, name="auth_max_start"),
    path("auth/max/verify", auth_views.max_verify, name="auth_max_verify"),
    path("auth/pin/set", auth_views.pin_set, name="auth_pin_set"),
    path("auth/pin/login", auth_views.pin_login, name="auth_pin_login"),
    path("auth/pin/reset-request", auth_views.pin_reset_request, name="auth_pin_reset_request"),
    path("auth/pin/reset-confirm", auth_views.pin_reset_confirm, name="auth_pin_reset_confirm"),
    path("auth/pin/change-request", auth_views.pin_change_request, name="auth_pin_change_request"),
    path("auth/pin/change-confirm", auth_views.pin_change_confirm, name="auth_pin_change_confirm"),
    path("auth/logout", auth_views.logout, name="auth_logout"),
    path("devices", auth_views.register_device, name="devices"),
    path("me", views.me, name="me"),
    path("me/avatar", views.me_avatar, name="me_avatar"),
    path("me/access", views.me_access, name="me_access"),
    path("me/subscription", views.me_subscription, name="me_subscription"),
    path("me/receipts", views.me_receipts, name="me_receipts"),
    path("me/feedback", views.me_feedback, name="me_feedback"),
    path("me/wishes", views.me_wishes, name="me_wishes"),
    path("groups", views.groups_list, name="groups"),
    path("groups/<int:group_id>/messages", views.group_messages, name="group_messages"),
    path("groups/<int:group_id>/read", views.group_mark_read, name="group_mark_read"),
    path("executor-roles", views.executor_roles, name="executor_roles"),
    path(
        "executor-roles/<int:role_id>/masters",
        views.role_masters,
        name="role_masters",
    ),
    path(
        "contractors/<int:contractor_id>/free-slots",
        views.contractor_free_slots,
        name="contractor_free_slots",
    ),
    path("work-requests", views.work_requests_list, name="work_requests"),
    path("work-requests/<int:pk>", views.work_request_detail, name="work_request_detail"),
    path(
        "work-requests/<int:pk>/confirm-booking",
        views.work_request_confirm_booking,
        name="work_request_confirm_booking",
    ),
    path(
        "work-requests/<int:pk>/confirm-amount",
        views.work_request_confirm_amount,
        name="work_request_confirm",
    ),
    path(
        "work-requests/<int:pk>/rate",
        views.work_request_rate,
        name="work_request_rate",
    ),
    path(
        "work-requests/<int:pk>/confirm-slot",
        views.work_request_confirm_slot,
        name="work_request_confirm_slot",
    ),
    path(
        "work-requests/<int:pk>/photos",
        views.work_request_add_photo,
        name="work_request_photos",
    ),
    path(
        "work-requests/<int:pk>/submit",
        views.work_request_submit,
        name="work_request_submit",
    ),
    path(
        "work-requests/<int:pk>/cancel",
        views.work_request_cancel,
        name="work_request_cancel",
    ),
    path(
        "work-requests/<int:pk>/mark-done",
        views.work_request_mark_done,
        name="work_request_mark_done",
    ),
    path(
        "work-requests/<int:pk>/report-payment",
        views.work_request_report_payment,
        name="work_request_report_payment",
    ),
    path(
        "work-requests/<int:pk>/commission",
        views.work_request_submit_commission,
        name="work_request_submit_commission",
    ),
    path(
        "work-requests/<int:pk>/cancel/",
        views.work_request_cancel,
        name="work_request_cancel_slash",
    ),
    path("me/executor", views.me_executor, name="me_executor"),
    path("executor/register", views.executor_register, name="executor_register"),
    path(
        "executor/role-proposals",
        views.executor_role_propose,
        name="executor_role_propose",
    ),
    path("executor/offers", views.executor_offers, name="executor_offers"),
    path(
        "executor/offers/<int:pk>/respond",
        views.executor_offer_respond,
        name="executor_offer_respond",
    ),
    path("executor/jobs", views.executor_jobs, name="executor_jobs"),
    path("executor/schedule", views.executor_schedule, name="executor_schedule"),
    path(
        "executor/schedule/busy",
        views.executor_busy_slot_create,
        name="executor_busy_slot_create",
    ),
    path(
        "executor/schedule/busy/<int:pk>",
        views.executor_busy_slot_delete,
        name="executor_busy_slot_delete",
    ),
    path(
        "executor/campaign-jobs",
        views.executor_campaign_jobs,
        name="executor_campaign_jobs",
    ),
    path(
        "executor/campaign-jobs/<int:pk>/respond",
        views.executor_campaign_job_respond,
        name="executor_campaign_job_respond",
    ),
    path(
        "work-requests/<int:pk>/propose-slots",
        views.work_request_propose_slots,
        name="work_request_propose_slots",
    ),
    path("collections", views.collections_list, name="collections"),
    path("collections/<int:pk>", views.collection_detail, name="collection_detail"),
    path(
        "collections/<int:pk>/receipt",
        views.collection_receipt,
        name="collection_receipt",
    ),
    path("onboarding", views.onboarding, name="onboarding"),
    path(
        "onboarding/steps/<slug:code>/complete",
        views.onboarding_complete_step,
        name="onboarding_step",
    ),
    path("notifications", views.notifications_list, name="notifications"),
    path(
        "notifications/<int:pk>/read",
        views.notification_read,
        name="notification_read",
    ),
]
